peso_payaso= int(112)
peso_muñeca= int(75)
numero_payasos= int(input("Ingrese el numero de payasos vendidos:"))
numero_muñecas= int(input("ingrese el numero de muñecas vendidas:"))
Peso_Total= (numero_payasos * peso_payaso) + (numero_muñecas * peso_muñeca)
print("El peso total del paquete que sera vendido es:", Peso_Total,"g")